-   id: helm
    name: helm (via docker)
    description: helm
    entry: /docker_entrypoint.sh
    language: docker
    args: [ /src/deploy/chart/test -f /src/deploy/chart/test/values.yaml]
    always_run: true
    pass_filenames: false
